# Generated by Django 4.1.6 on 2023-02-12 13:40

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img_id_card',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.herafi_id_card_img_uploader),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.profile_img_uploader),
        ),
    ]
