# Generated by Django 4.1.6 on 2023-02-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_banned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.BooleanField(help_text='1 = female, 0 = male'),
        ),
    ]
