# Generated by Django 4.1.6 on 2023-02-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.BooleanField(help_text='1(selected or True) = female, 0(not-selected or False)  = male'),
        ),
    ]
