# Generated by Django 4.1.6 on 2023-02-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bonuses_points',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
