# Generated by Django 4.1.6 on 2023-02-12 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_info', '0006_alter_city_id'),
        ('accounts', '0019_profile_city_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main_info.city'),
        ),
    ]
