# Generated by Django 4.1.6 on 2023-02-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_profile_city_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='HerafiInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.ImageField(upload_to='')),
                ('requests', models.ImageField(upload_to='')),
                ('price_of_preview', models.DecimalField(decimal_places=2, max_digits=5)),
                ('experiences', models.DecimalField(decimal_places=1, max_digits=3)),
                ('phone_number', models.CharField(max_length=11)),
                ('bio', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
