# Generated by Django 4.1.6 on 2023-02-12 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_info', '0006_alter_city_id'),
        ('accounts', '0021_herafiinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='herafiinformation',
            name='job_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main_info.job'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='herafiinformation',
            name='profile_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
            preserve_default=False,
        ),
    ]
