# Generated by Django 4.1.6 on 2023-02-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_herafiinformation_job_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herafiinformation',
            name='requests',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='herafiinformation',
            name='views',
            field=models.IntegerField(),
        ),
    ]
