# Generated by Django 4.1.6 on 2023-02-12 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_info', '0007_alter_job_id'),
        ('accounts', '0024_alter_herafiinformation_experiences_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herafiinformation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='herafiinformation',
            name='job_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main_info.job'),
        ),
    ]
