# Generated by Django 4.1.6 on 2023-02-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_herafiinformation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
