# Generated by Django 4.1.6 on 2023-02-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_accounttype_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferredherafies',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
