# Generated by Django 4.1.6 on 2023-03-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_alter_profile_city_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='herafiinformation',
            name='people_rated_num',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='herafiinformation',
            name='percentage_ratings',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
