# Generated by Django 4.1.6 on 2023-03-05 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_herafiinformation_people_rated_num_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='herafiinformation',
            old_name='people_rated_num',
            new_name='people_rated',
        ),
    ]
