# Generated by Django 4.1.6 on 2023-03-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_rename_people_rated_num_herafiinformation_people_rated'),
    ]

    operations = [
        migrations.AddField(
            model_name='herafiinformation',
            name='stars',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
