# Generated by Django 4.1.6 on 2023-02-12 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district1', models.CharField(max_length=50)),
                ('district2', models.CharField(max_length=50)),
                ('district3', models.CharField(max_length=50)),
                ('district4', models.CharField(max_length=50)),
                ('district5', models.CharField(max_length=50)),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_info.city')),
            ],
        ),
    ]
