# Generated by Django 4.1.6 on 2023-02-12 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_info', '0002_citydistrict'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citydistrict',
            old_name='district1',
            new_name='district',
        ),
        migrations.RemoveField(
            model_name='citydistrict',
            name='district2',
        ),
        migrations.RemoveField(
            model_name='citydistrict',
            name='district3',
        ),
        migrations.RemoveField(
            model_name='citydistrict',
            name='district4',
        ),
        migrations.RemoveField(
            model_name='citydistrict',
            name='district5',
        ),
    ]
