# Generated by Django 4.1.6 on 2023-02-12 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_info', '0003_rename_district1_citydistrict_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citydistrict',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_info.city'),
        ),
    ]
