# Generated by Django 4.1.6 on 2023-02-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_comment_alter_ticket_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
