# Generated by Django 4.1.6 on 2023-02-12 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_info', '0007_alter_job_id'),
        ('tickets', '0006_ticket_schedule_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='job_category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_info.job'),
            preserve_default=False,
        ),
    ]
