# Generated by Django 4.1.6 on 2023-02-12 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_preferredherafies_id'),
        ('tickets', '0008_ticket_city_district_ticket_city_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='herafi_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.herafiinformation'),
            preserve_default=False,
        ),
    ]
