# Generated by Django 4.1.6 on 2023-03-03 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_alter_profile_city_id'),
        ('tickets', '0013_remove_ticket_schedule_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='herafi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.herafiinformation'),
            preserve_default=False,
        ),
    ]
