# Generated by Django 4.1.6 on 2023-03-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_alter_ticket_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
