# Generated by Django 4.1.6 on 2023-03-05 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_alter_ticket_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='datetime',
        ),
        migrations.AddField(
            model_name='ticket',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
